name: ci-development

on:
  pull_request:
    # When something wants to get into main this will trigger
    # Will always be through a pull request because main is protected
    branches: [ main ]
    paths:
      - 'app/**'

run-name: >-
  ci – ${{ github.head_ref }} by @${{ github.actor }} 
  (pr #${{ github.event.pull_request.number }}, run #${{ github.run_number }})

jobs:
  # Used to decide which stack to deploy
  stacks:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      matrix: ${{ steps.build.outputs.matrix }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # This checks if there are changes in the stack
      # This allows to only deploy if there are changes
      # It makes the default CD more efficient
      - name: Detect changed paths
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            server:
              - 'app/**'

      # Based on the previous step, the matrix is decided
      # If the matrix is empty, deployment is skipped
      - name: Build matrix from changes
        id: build
        shell: bash
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            arr=('"processor"' '"server"')
          else
            arr=()
            [[ "${{ steps.changes.outputs.processor }}" == 'true' ]] && arr+=('"processor"')
            [[ "${{ steps.changes.outputs.server }}" == 'true' ]] && arr+=('"server"')
          fi

          json=$(printf '%s\n' "${arr[@]}" | jq -R . | jq -s -c .)
          echo "matrix=${json}" >> "$GITHUB_OUTPUT"

  ci:
    needs: stacks
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        stack: ${{ fromJSON(needs.stacks.outputs.matrix) }}
    env:
      DIR: app/${{ matrix.stack }}

    defaults:
      run:
        working-directory: ${{ env.STACK_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup single environment with uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.14"
          enable-cache: true

      - name: Symlink uv to local path
        run: |
          mkdir -p ~/.local/bin
          ln -sf $(which uv) ~/.local/bin/uv

      - name: Sync environment with uv (per stack)
        run: uv sync --all-extras --dev --locked

      - name: Run pre-commit hooks
        uses: tox-dev/action-pre-commit-uv@v1
        with:
          # Only run tagged manual.
          # Prevents from pytest running.
          # Linting should be done on single version.
          # Testing on all version.
          extra_args: >-
            --all-files
            --hook-stage manual

      - name: Run tests with coverage
        run: uv run pytest



