POST http://127.0.0.1:8000/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic ...

grant_type=client_credentials&client_id=1&client_secret=2


### 
POST http://127.0.0.1:8000/token
Content-Type: application/json
Authorization: Basic ...

{"grant_type" : "password", "username" : "x", "password" : "y"}