POST http://127.0.0.1:8000/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic ...

grant_type=refresh_token&refresh_token=...

###
POST http://127.0.0.1:8000/token
Content-Type: application/json
Authorization: Basic ...

{"grant_type" : "refresh_token", "refresh_token" : "f6fe267a760597066f404caa77f31329ce55eeaf187e4c0506137e841d48fa6e"}